---
version: "3.7"
services:
  bandstand:
    build: /Users/mp/devel/observability-dev/apps/automation/bandstand/
    container_name: bandstand
    environment:
      APP_TOKEN: test_token
      APP_SECRET: test_secret
    ports:
      - "8000:8000"
    networks:
      apm-pipeline-library:
  jenkins:
    build: .
    container_name: jenkins-lint
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
      CASC_VAULT_ENGINE_VERSION: "1"
      CASC_VAULT_PATHS: |
        secret/jcasc/localhost/base,secret/jcasc/localhost/apm-ci
      CASC_VAULT_TOKEN: ${VAULT_TOKEN}
      CASC_VAULT_URL: ${VAULT_ADDR:-https://secrets.elastic.co:8200}
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UsageStatistics.disabled=true
    volumes:
      - type: bind
        source: /Users/mp/devel/apm-agent-java
        target: /apm-agent-java
        read_only: true
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
      - type: bind
        source: ./configs/jenkins.yaml
        target: /var/jenkins_home/casc_configs/jenkins.yaml
        read_only: true
      - type: bind
        source: ../.
        target: /var/pipeline-library
        read_only: true
    ports:
      - "18080:8080"
      - "50000:50000"
    networks:
      apm-pipeline-library:

volumes:
  jenkins_home:

networks:
  apm-pipeline-library:
    driver: bridge
